### ISSUE TITLE
Not listed on CodebaseShow Real world example apps

### ISSUE THREAD

**Issue by rdhainaut** [AlexBrohshtut/vue-ts-realworld-app#13]
I have found your repo in digging the "conduit" real world example and I have not found your repo.
Fortunately it was referenced on other vue js samples.

You can see your project is not in the list
https://codebase.show/projects/realworld?category=frontend&language=typescript
I have look this project and it's a good job. It the sample that I prefer.
I love the Class + Decorator approach, it s really the most readable and easy to structure for me.

You should definitively submit your project on the codebase.show to make it discover and show a Typescript Class + Decorator implementation of Vuejs !

**Comment by AlexBrohshtut** [comment]
Thanks for the suggestion and a feedback, I've added it there:)
