### ISSUE TITLE
API Domain change

### ISSUE THREAD

**Issue by geromegrignon** [AlexBrohshtut/vue-ts-realworld-app#23]
Hello!

Due to governance changes, we are now using the `realworld.io` domain for the RealWorld demo (both client and API).
Requests from `conduit.productionready.io` are redirected to `api.realworld.io`, but such a redirection might lead to inconsistent responses.

We encourage domain change for the community.
If this repository is maintained anymore, we'll consider hosting a demo of your implementation in a few weeks with the domain change.

The demo link will be added to the RealWorld documentation.

**Comment by AlexBrohshtut** [comment]
https://github.com/AlexBrohshtut/vue-ts-realworld-app/commit/27cd36e43b2de1c40d79b8767d0cb416bcbd3651
Done, thanks for keeping me in the loop, @geromegrignon :)

**Comment by geromegrignon** [comment]
Hey @AlexBrohshtut, you're welcome, you are part of RealWorld Community!
