### ISSUE TITLE
Could you please add links to other vue related implementations?

### ISSUE THREAD

**Issue by levchak0910** [AlexBrohshtut/vue-ts-realworld-app#9]
The goal of this to have all implementations linked with each other

Other implementations:
https://github.com/gothinkster/vue-realworld-example-app - vue2, js
https://github.com/devJang/nuxt-realworld - nuxt, ts, composition api
https://github.com/mutoe/vue3-realworld-example-app - vue3, vite, ts, composition api
https://github.com/levchak0910/vue3-ssr-realworld-example-app - vue3, ssr

**Comment by AlexBrohshtut** [comment]
Good idea, added it.
